In [6]:
#Name: Kerry Gip
#Date: 1/31/2021

import random

#PART 1: Binary search simulation  (Power of divide by 2) : (5 points)
     
#https://www.geeksforgeeks.org/python-program-for-binary-search/ making sure I have the binary search correct        
def binarySearch(someList, rando):
    #define parameters
    count = 0
    low = 0
    mid = 0
    high = len(someList)
    found = False
    
    while (found != True):
        mid = (low+high)//2
        
        #checks if rando is in the right array
        if (someList[mid] < rando):
            #makes new low at the halfway point
            low = mid+1
            count = count +1
#            print("Random (", rando, ") is higher than mid. low = ", low, ", high = ", high, " count = ", count)
        #else rando is in the left array
        elif (someList[mid] > rando):
            #high point starts at less than middle
            high = mid-1
            count = count +1
#            print("Random (", rando, ") is lower than mid. low = ", low, ", high = ", high, " count = ", count)
        
        #(someList[mid] == rando)
        else:
            found = True
            
    
    return count
#guess the number loop?
        #count = count/10000


#function call
def countNum(size):
    someList = list(range(size))
    count = 0
    for i in range(size):
    #gen random
        rando = random.randrange(1000)
    # binsearch: countS
        count += binarySearch(someList, rando)
    return count
    

print("Total count for 10k: ", countNum(10000), "Average count: ", countNum(10000)/10000)
print("Total count for 1000:", countNum(1000), "Average count: ", countNum(1000)/10000)
print("Total count for 1 million:", countNum(1000000), "Average count: ", countNum(1000000)/10000)

#results = binarySearch(someList, rando)

#print results
#print("First number is:", rando, "It took: ", results,  "tries to match up")

Total count for 10k:  113314 Average count:  11.3879
Total count for 1000: 7981 Average count:  0.8068
Total count for 1 million: 17955137 Average count:  1795.5404


Total count for 10k:  113314 Average count:  11.3879
Total count for 1000: 7981 Average count:  0.8068
Total count for 1 million: 17955137 Average count:  1795.5404

In [12]:
#PART 2: Writing a simple timer function (5 points)

#time function needs time library
import time

#creating function for input argument
def findPrime(maxNum):
    newList = []
    total = 0
    for i in range(2,maxNum):
    #checks to see if it can only divide by itself
        for j in range(2, i):
        #maxNum divde by it's position then it is not prime
            if i % j == 0:
                break
            else:
                newList.append(i)
                break
    print("List of all the prime numers are: ", newList)
    

#passing a funciton as an input argument along with specified function arguments
def timeEfficiency(maxNum):
    start = time.time()
    findPrime(maxNum)
    end = time.time()
    
    
    #print results
    print("Starts at: ", start)
    print("Ends at: ", end)
    print("Time taken: ", end- start)


def main():
    maxNum = eval(input("What number do you want to find the prime number of: "))
    #print(timeEfficiency())
    timeEfficiency(maxNum)
    
main()
    
    
    
    

What number do you want to find the prime number of: 100
List of all the prime numers are:  [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
Starts at:  1612655472.9913425
Ends at:  1612655472.9923396
Time taken:  0.0009970664978027344


What number do you want to find the prime number of: 100
List of all the prime numers are:  [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
Starts at:  1612655472.9913425
Ends at:  1612655472.9923396
Time taken:  0.0009970664978027344

In [10]:
#PART 3: Another number guessing game : (10 points)
import random


#brute force algorithm
def bruteForce():

    rando = []
    for i in range(3):
        rando.append(random.randrange(10))
    brute = list(range(3))

    tries = 0
    bruteList = [] 
    #3 for loops to iterate each number in the array
    for i in range(10):
        for j in range(10):
            for k in range(10):
                for m in range(10): #gets tries to 10k
                #if i,j,k != rando[1,2,3], then + 1 until it matches
                    if i != rando[0]:
                        i = i+1
                        tries = tries+1
                # if matches, then replace i with brute
                    else: 
                        brute[0] = i
                    
                    if j != rando[1]:
                        j + j+1
                        tries = tries +1
                    else:
                        brute[1] = j
                    
                    if k != rando[2]:
                        k = k+1
                        tries = tries +1 
                    else:
                        brute[2] = k
                    bruteList.append(tries)      
    return bruteList  
    
#calling funtions
bruteCall = bruteForce() #call the list of tries

#Deterministic brute-force algorithm:
print("\nPURE BRUTE FORCE NUMBERS")
print("Number of Tries: 10000")
print("Highest number of guess in a try: ", max(bruteCall))
print("Lowest number of guess in a try:", min(bruteCall))
print("Number of Correct Tries: 10000")
print("Average number of tries:", (sum(bruteCall))/10000)

import random

def algorithm():

    rando = random.randrange(10),random.randrange(10),random.randrange(10)
    algo = random.randrange(10),random.randrange(10),random.randrange(10)

    tries = 0
    correctTries = []
    
    #also had it as algo != rando
    while((tries< 10000)):
        if rando == algo:
         
            break
        else:
            algo = random.randrange(10),random.randrange(10),random.randrange(10)
            tries = tries+ 1
                
        #storing tries in a list and just use built in list functions 
        correctTries.append(tries)
    return correctTries

#algo call    
algoCall = algorithm()

#Complete pure random algorithm
print("\nPURE RANDOM ALGORITHM NUMBERS")
print("Number of Tries: 10000")
print("Highest number of guess in a try: ", max(algoCall))
print("Lowest number of guess in a try: ", min(algoCall))
print("Number of Correct Tries: ", 10000- len(algoCall))
print("Average number of tries: ", sum(algoCall)/10000)



PURE BRUTE FORCE NUMBERS
Number of Tries: 10000
Highest number of guess in a try:  20106
Lowest number of guess in a try: 3
Number of Correct Tries: 10000
Average number of tries: 8847.6496

PURE RANDOM ALGORITHM NUMBERS
Number of Tries: 10000
Highest number of guess in a try:  1279
Lowest number of guess in a try:  1
Number of Correct Tries:  8721
Average number of tries:  81.856


PURE BRUTE FORCE NUMBERS

Number of Tries: 10000

Highest number of guess in a try:  22600

Lowest number of guess in a try: 2

Number of Correct Tries: 10000

Average number of tries: 10860.21


PURE RANDOM ALGORITHM NUMBERS

Number of Tries: 10000

Highest number of guess in a try:  889

Lowest number of guess in a try:  1

Number of Correct Tries:  9111

Average number of tries:  39.5605

In [4]:
#PART 4: Display top N number of words in descending order of a file

def main():
         
    count = 0
    keepLooping = True
    newDict = dict()
    
    #infile check
    while keepLooping:
        try:
            infileName = input("Enter the file name: ")
            infile= open(infileName, "r")
            keepLooping = False
        except FileNotFoundError:
            print("Invalid file name, try again")
    
    #infile read/strip/split/lower 
    #reads through the infile and adds to dictionary
    for line in infile:
        words = line.strip().lower().split()
        for word in words:
            if word in newDict:
                newDict[word] = newDict[word] + 1
                #if not in dicitonary, assign it  value 1 
            else:
                newDict[word] = 1

    #print results
    print("Words and their frequencies")
    for key in list(newDict.keys()):
        print(key, newDict[key])
main()       

Enter the file name: Lincoln.txt
Invalid file name, try again
Enter the file name: Lincoln.txt
Invalid file name, try again


KeyboardInterrupt: Interrupted by user

Enter the file name: Lincoln.txt                                                                                                                
Words and their frequencies                                                                                                                     
portion 1                                                                                                                                       
dedicated 3                                                                                                                                     
here, 2                                                                                                                                         
war. 1                                                                                                                                          
all 1                                                                                                                                           
consecrated 1                                                                                                                                   
it, 1                                                                                                                                           
did 1                                                                                                                                           
fitting 1                                                                                                                                       
should 1                                                                                                                                        
be 2                                                                                                                                            
conceived 2                                                                                                                                     
dedicate 2                                                                                                                                      
brought 1                                                                                                                                       
-- 7                                                                                                                                            
met 1                                                                                                                                           
to 8                                                                                                                                            
place 1                                                                                                                                         
any 1                                                                                                                                           
come 1                                                                                                                                          
men, 1                                                                                                                                          
field, 1                                                                                                                                        
resolve 1                                                                                                                                       
power 1                                                                                                                                         
now 1                                                                                                                                           
from 2                                                                                                                                          
score 1                                                                                                                                         
birth 1                                                                                                                                         
endure. 1                                                                                                                                       
note, 1                                                                                                                                         
engaged 1                                                                                                                                       
equal. 1 
lives 1                                                                                                                                         
we 10                                                                                                                                           
whether 1                                                                                                                                       
but 1                                                                                                                                           
and 6                                                                                                                                           
remaining 1                                                                                                                                     
that 13                                                                                                                                         
shall 3                                                                                                                                         
gave 2                                                                                                                                          
this. 1                                                                                                                                         
under 1                                                                                                                                         
detract. 1                                                                                                                                      
god, 1                                                                                                                                          
new 2                                                                                                                                           
dead, 1                                                                                                                                         
world 1                                                                                                                                         
proper 1                                                                                                                                        
forget 1                                                                                                                                        
hallow 1                                                                                                                                        
died 1                                                                                                                                          
little 1                                                                                                                                        
task 1                                                                                                                                          
is 3                                                                                                                                            
add 1                                                                                                                                           
can 5                                                                                                                                           
they 3                                                                                                                                          
for 5                                                                                                                                           
measure 1                                                                                                                                       
larger 1                                                                                                                                        
civil 1                                                                                                                                         
people, 3                                                                                                                                       
in 4                                                                                                                                            
highly 1

devotion 2                                                                                                                                      
living, 1                                                                                                                                       
unfinished 1                                                                                                                                    
their 1                                                                                                                                         
consecrate 1                                                                                                                                    
war, 1                                                                                                                                          
advanced. 1                                                                                                                                     
forth 1                                                                                                                                         
or 2                                                                                                                                            
years 1                                                                                                                                         
living 1                                                                                                                                        
what 2                                                                                                                                          
above 1                                                                                                                                         
great 3                                                                                                                                         
government 1                                                                                                                                    
those 1                                                                                                                                         
resting 1                                                                                                                                       
of 5                                                                                                                                            
increased 1                                                                                                                                     
struggled 1                                                                                                                                     
cause 1                                                                                                                                         
liberty, 1                                                                                                                                      
not 5                                                                                                                                           
nobly 1                                                                                                                                         
who 3                                                                                                                                           
battle-field 1                                                                                                                                  
which 2                                                                                                                                         
fathers 1                                                                                                                                       
rather, 1                                                                                                                                       
poor 1                                                                                                                                          
remember 1                                                                                                                                      
brave 1                                                                                                                                         
have 5
last 1                                                                                                                                          
men 1                                                                                                                                           
on 2                                                                                                                                            
nation, 3                                                                                                                                       
by 1                                                                                                                                            
nation 2                                                                                                                                        
here. 1                                                                                                                                         
do 1                                                                                                                                            
rather 1                                                                                                                                        
honored 1                                                                                                                                       
long 2                                                                                                                                          
are 3                                                                                                                                           
never 1                                                                                                                                         
sense, 1                                                                                                                                        
will 1                                                                                                                                          
altogether 1                                                                                                                                    
freedom 1                                                                                                                                       
so 3                                                                                                                                            
say 1                                                                                                                                           
proposition 1                                                                                                                                   
might 1                                                                                                                                         
fought 1                                                                                                                                        
perish 1                                                                                                                                        
this 3                                                                                                                                          
take 1                                                                                                                                          
vain 1                                                                                                                                          
far 2                                                                                                                                           
seven 1
us 3                                                                                                                                            
a 7                                                                                                                                             
ago 1                                                                                                                                           
thus 1                                                                                                                                          
continent, 1                                                                                                                                    
live. 1                                                                                                                                         
dead 2                                                                                                                                          
created 1                                                                                                                                       
four 1                                                                                                                                          
work 1                                                                                                                                          
it 4                                                                                                                                            
but, 1                                                                                                                                          
the 11                                                                                                                                          
earth. 1                                                                                                                                        
our 2                                                                                                                                           
ground. 1                                                                                                                                       
full 1                                                                                                                                          
nor 1                                                                                                                                           
as 1                                                                                                                                            
testing 1                                                                                                                                       
final 1                                                                                                                                         
these 2                                                                                                                                         
before 1                                                                                                                                        
here 5                                                                                                                                          
dedicated, 1 

In [ ]:
#Extra Credit Problem 1 (5 points)

#Decorator pattern allows a user to add new functionality to an existing object without altering its structure. 
#This type of #design pattern comes under structural pattern as this pattern acts as a wrapper to existing class.
#[decorator example][https://dev.to/apcelent/python-decorator-tutorial-with-example-529f#:~:text=Python%20decorator%20are%20the%20function,match%20the%20function%20to%20decorate.]
import time
    
    


#Extra Credit Problem 2
Answer the following questions in the Python decorator context.  
Your answers should be written  in a Markdown file.  The quality of answers matters!!

#1. What is higher-order function and how it is different from functor? @wikipedia
A higher order function either takes one or more functions as arguments or returns a function as its result to the caller
A functor is constantly mistaken for a higher order function and vice versa. A functor is mapping between category theories.
[https://www.geeksforgeeks.org/functors-in-cpp/] 
Functors can also be objects that can be treated as though they are a function or function pointer. 
Functors are most commonly used along with STL's. It acts like a function and can be called by overloading the () operator 

#2. What are First-class objects?  What is the significance of functions being First-class objects? 
[First class object source][https://stackoverflow.com/questions/245192/what-are-first-class-objects#:~:text=A%20first%20class%20object%20is,being%20storable%20in%20variables]
A first class object is an entity that can be dynamically created, destroyed, passed to a function, returned as a value, 
and have all the rights as other variables in the programming language have
Overriding a function makes an object first class, same as function pointers. In Python, both classes and it's objects are first class
It implies that it can be expressed as an anonymous value, storable in variables, data structures, being printable, and
many others


#3. What are inner functions?  What is the major benefit of inner functions and why is it important for decorator 
[Inner function source 1][https://stackabuse.com/python-nested-functions/#:~:text=An%20inner%20function%20is%20simply,but%20it%20cannot%20change%20them.&text=For%20instance%2C%20an%20inner%20function,from%20what%20happens%20outside%20it.]
Inner functions are a function within a function. The inner function is able to acces variables that have been defined within the scope of the outer function but it cannot change it. 
[Inner Function source 2][https://realpython.com/inner-functions-what-are-they-good-for/]
Inner functions can also protect functions from everything outside, like encapsulation and is really userful for closures
It is important for decorators because it allows you to wrap another function to extend the behavior of the wrapped function without modifying it. Inner  functions go inside of decorator functions 


#4. Why @ symbol is called syntactic sugar?  What's the biggest advantage of using it when decorators are used? 
Syntactic sugar is a way to make things easier to read for human eyes. It utilizes the decorator. It is a shortcut way to call 
a decorator function 
As for why using @, I'd say that it is because of the twitter statement of "Don't @ me" which means to not tag that person in the comments. So with that in mind, using the @ symbol just means to call the funciton. 
[Byte order size][https://docs.python.org/3/library/struct.html#index-1]
With this new information, the @ symbol is used since it has a native byte order and a native size and alignment. This means that it takes up slightly less space and memory. 

#5. How would it help Python's weak OOP encapsulation of Class?  (Hint: google "Python @Property decorator")
[Better encapsulation in python][https://medium.com/better-programming/encapsulation-in-python-d76212d52478]
Python has a weak encapsulation because everything is inherently public. Weak encapsulation means that it is performed by convention and not due to the language itself. However with inner functions and decorators, it can help wrap functions within a function and can protect the function from outside variables/functions. 
[@property][https://www.tutorialsteacher.com/python/property-decorator]
The @property decorator makes the method a private getter method by convention. It needs an @__.setter decorator attached to it. 